<?php
defined( 'ABSPATH' ) || exit;

$templates['statistics-1'] = array();
$templates['statistics-1']['name'] = esc_html__( 'Statistics', 'total' ) . ' 1';
$templates['statistics-1']['category'] = 'statistics';
$templates['statistics-1']['content'] = <<<CONTENT
[vc_row remove_bottom_col_margin="true" css=".vc_custom_1627254415856{padding-top: 60px !important;padding-bottom: 70px !important;}"][vc_column][vcex_heading text="Why Choose Company X?" text_align="center" tag="h2" font_size="30px" font_weight="bold"][vcex_spacing size="20px"][vc_column_text width="650px" align="center" text_align="center"]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et justo ultricies, mattis felis quis, laoreet eros. Vivamus pellentesque mauris orci. Ut vitae congue ligula.[/vc_column_text][vcex_spacing size="50px"][vcex_grid_container align_items="center" justify_items="center" columns_lg="" columns_md="3" gap="40px"][vcex_milestone number="8" caption="Years in Service" caption_color="#222222" number_color="#222222" caption_size="1em" number_weight="600" caption_font="500" after="+"][vcex_milestone number="16" caption="Products &amp; Services" caption_color="#222222" number_color="#222222" caption_size="1em" number_weight="600" caption_font="500" after="+"][vcex_milestone number="200" caption="Happy Clients" caption_color="#222222" number_color="#222222" after="+" caption_size="1em" number_weight="600" caption_font="500"][/vcex_grid_container][/vc_column][/vc_row]
CONTENT;

$templates['statistics-2'] = array();
$templates['statistics-2']['name'] = esc_html__( 'Statistics', 'total' ) . ' 2';
$templates['statistics-2']['category'] = 'statistics';
$templates['statistics-2']['content'] = <<<CONTENT
[vc_row css=".vc_custom_1627254452036{padding-top: 60px !important;padding-bottom: 30px !important;}"][vc_column width="1/2"][vcex_heading text="We are the experts in the industry, look no further." tag="h2" font_size="30px" font_weight="700"][vcex_spacing size="20px"][vc_column_text]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et justo ultricies, mattis felis quis, laoreet eros. Vivamus pellentesque mauris orci. Ut vitae congue ligula donec malesuada enim tristique.[/vc_column_text][vcex_spacing][vcex_button font_padding="top:15px|right:25px|bottom:15px|left:25px" color="black" border_radius="0px" text_transform="uppercase" font_weight="semibold" letter_spacing="1.5px" custom_hover_background="accent" font_size=".9em"]See Pricing[/vcex_button][/vc_column][vc_column width="1/2"][vcex_grid_container align_items="center" columns_lg="" columns_sm="2"][vcex_milestone style="bordered" padding_all="40px" number="15" caption="Years Experience" caption_color="#222222" number_color="#222222" caption_size="1.2em" number_weight="900" caption_font="600" border_color="#e0e0e0"][vcex_milestone style="bordered" padding_all="40px" number="26" caption="Awards Received" caption_color="#222222" number_color="#222222" caption_size="1.2em" number_weight="900" caption_font="600" border_color="#e0e0e0"][vcex_milestone style="bordered" padding_all="40px" number="37" caption="Certifications Earned" caption_color="#222222" number_color="#222222" caption_size="1.2em" number_weight="900" caption_font="600" border_color="#e0e0e0"][vcex_milestone style="bordered" padding_all="40px" number="70" caption="Projects Completed" caption_color="#222222" number_color="#222222" caption_size="1.2em" number_weight="900" caption_font="600" border_color="#e0e0e0"][/vcex_grid_container][/vc_column][/vc_row]
CONTENT;

$templates['statistics-3'] = array();
$templates['statistics-3']['name'] = esc_html__( 'Statistics', 'total' ) . ' 3';
$templates['statistics-3']['category'] = 'statistics';
$templates['statistics-3']['content'] = <<<CONTENT
[vc_row full_width="stretch_row" remove_bottom_col_margin="true" css=".vc_custom_1627248526292{padding-top: 10% !important;padding-bottom: 10% !important;background-color: #222222 !important;}"][vc_column][vcex_heading text="Project Goals" align="center" tag="h2" font_size="d:35px|pl:30px" font_weight="700" color="#ffffff" width="700px" text_align="center"][vcex_spacing size="20px"][vc_column_text color="rgba(255,255,255,0.6)" width="700px" align="center" text_align="center"]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et justo ultricies, mattis felis quis, laoreet eros. Vivamus pellentesque mauris orci. Ut vitae congue ligula donec malesuada enim tristique.[/vc_column_text][vcex_spacing size="40px"][vcex_grid_container align_items="center" columns_lg="4" columns_sm="2" gap="30px"][vcex_milestone padding_all="40px" number="16" caption="Years Active" caption_color="#ffffff" number_color="#ffffff" caption_size="1.2em" number_weight="400" border_color="#e0e0e0" background_color="rgba(255,255,255,0.08)" number_size="60px" caption_font="normal"][vcex_milestone padding_all="40px" caption="Money Raised" caption_color="#ffffff" number_color="#ffffff" caption_size="1.2em" number_weight="400" border_color="#e0e0e0" background_color="rgba(255,255,255,0.08)" number_size="60px" caption_font="normal" before="$" after="K"][vcex_milestone padding_all="40px" number="4" caption="People reached" caption_color="#ffffff" number_color="#ffffff" caption_size="1.2em" number_weight="400" border_color="#e0e0e0" background_color="rgba(255,255,255,0.08)" number_size="60px" caption_font="normal" after="M"][vcex_milestone padding_all="40px" number="36" caption="Schools Opened" caption_color="#ffffff" number_color="#ffffff" caption_size="1.2em" number_weight="400" border_color="#e0e0e0" background_color="rgba(255,255,255,0.08)" number_size="60px" caption_font="normal" after="+"][/vcex_grid_container][/vc_column][/vc_row]
CONTENT;

$templates['statistics-4'] = array();
$templates['statistics-4']['name'] = esc_html__( 'Statistics', 'total' ) . ' 4';
$templates['statistics-4']['category'] = 'statistics';
$templates['statistics-4']['content'] = <<<CONTENT
[vc_row full_width="stretch_row" content_placement="middle" remove_bottom_col_margin="true" css=".vc_custom_1627248746792{padding-top: 60px !important;padding-bottom: 60px !important;background-color: #f7f7f7 !important;}"][vc_column width="1/2"][vcex_heading text="We've come along way, check out our milestones." tag="h2" font_size="30px" font_weight="700"][vcex_spacing size="20px"][vc_column_text]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et justo ultricies, mattis felis quis, laoreet eros. Vivamus pellentesque mauris orci. Ut vitae congue ligula donec malesuada enim tristique.[/vc_column_text][vcex_spacing][vcex_button font_padding="top:15px|right:25px|bottom:15px|left:25px" color="black" border_radius="0px" text_transform="uppercase" font_weight="semibold" letter_spacing="1px"]Call to Action[/vcex_button][vcex_spacing size="40px"][/vc_column][vc_column width="1/2"][vcex_grid_container align_items="center" columns_lg="" columns_sm="2" gap="30px"][vcex_milestone padding_all="40px" shadow="shadow-lg" shadow_hover="shadow-xl" number="76" caption="Goals Reached" enable_icon="true" icon_position="top" caption_color="#222222" number_color="#222222" caption_size="1.2em" number_weight="600" caption_font="500" border_color="#e0e0e0" background_color="#ffffff" after="%" icon="ticon ticon-flag" icon_color="#222222" border_radius="10px" icon_size="30px" number_size="35px"][vcex_milestone padding_all="40px" shadow="shadow-lg" shadow_hover="shadow-xl" number="26" caption="Money Raised" enable_icon="true" icon_position="top" caption_color="#222222" number_color="#222222" caption_size="1.2em" number_weight="600" caption_font="500" border_color="#e0e0e0" background_color="#ffffff" icon="ticon ticon-heart" icon_color="#222222" border_radius="10px" number_size="35px" icon_size="30px" before="$" after="K"][vcex_milestone padding_all="40px" shadow="shadow-lg" shadow_hover="shadow-xl" number="8" caption="Facebook Likes" enable_icon="true" icon_position="top" caption_color="#222222" number_color="#222222" caption_size="1.2em" number_weight="600" caption_font="500" border_color="#e0e0e0" background_color="#ffffff" after="M" icon="ticon ticon-thumbs-up" icon_color="#222222" border_radius="10px" number_size="35px" icon_size="30px"][vcex_milestone padding_all="40px" shadow="shadow-lg" shadow_hover="shadow-xl" number="130" caption="Locations Created" enable_icon="true" icon_position="top" caption_color="#222222" number_color="#222222" caption_size="1.2em" number_weight="600" caption_font="500" border_color="#e0e0e0" background_color="#ffffff" after="+" icon="ticon ticon-map-marker" icon_color="#222222" border_radius="10px" number_size="35px" icon_size="30px"][/vcex_grid_container][/vc_column][/vc_row]
CONTENT;

$templates['statistics-5'] = array();
$templates['statistics-5']['name'] = esc_html__( 'Statistics', 'total' ) . ' 5';
$templates['statistics-5']['category'] = 'statistics';
$templates['statistics-5']['content'] = <<<CONTENT
[vc_row css=".vc_custom_1627254491296{margin-top: 40px !important;}"][vc_column][vcex_heading text="Our Current Progress" text_align="center" tag="h2" font_size="30px" font_weight="700"][vcex_spacing size="15px"][vc_column_text width="650px" align="center" text_align="center"]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et justo ultricies, mattis felis quis, laoreet eros. Vivamus pellentesque mauris orci. Ut vitae congue ligula.[/vc_column_text][vcex_spacing size="10px"][/vc_column][/vc_row][vc_row][vc_column width="2/5"][vcex_image source="external" external_image="{$ph_portrait}"][/vc_column][vc_column width="3/5"][vcex_heading text="Projects Completed" bottom_margin="15px" tag="h3" font_size="18px" font_weight="bold" color="#222222"][vcex_skillbar title="" percentage="36" bottom_margin="15px" box_shadow="false" container_height="20px" percentage_font_size="10px" color="#666666" background="#eeeeee"][vc_column_text]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et justo ultricies, mattis felis quis, laoreet eros. Vivamus pellentesque mauris orci. Ut vitae congue ligula. Donec malesuada enim tristique, aliquet ligula vestibulum, placerat lacus.[/vc_column_text][vcex_spacing][vcex_heading text="Schools Built" bottom_margin="15px" tag="h3" font_size="18px" font_weight="bold" color="#222222"][vcex_skillbar title="" percentage="70" bottom_margin="15px" box_shadow="false" color="#4c4c4c" container_height="20px" percentage_font_size="10px" background="#eeeeee"][vc_column_text]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et justo ultricies, mattis felis quis, laoreet eros. Vivamus pellentesque mauris orci. Ut vitae congue ligula. Donec malesuada enim tristique, aliquet ligula vestibulum, placerat lacus.[/vc_column_text][vcex_spacing][vcex_heading text="Trademarks Filed" bottom_margin="15px" tag="h3" font_size="18px" font_weight="bold" color="#222222"][vcex_skillbar title="" percentage="90" bottom_margin="15px" box_shadow="false" color="#222222" container_height="20px" percentage_font_size="10px" background="#eeeeee"][vc_column_text]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et justo ultricies, mattis felis quis, laoreet eros. Vivamus pellentesque mauris orci. Ut vitae congue ligula. Donec malesuada enim tristique, aliquet ligula vestibulum, placerat lacus.[/vc_column_text][/vc_column][/vc_row]
CONTENT;

$templates['statistics-6'] = array();
$templates['statistics-6']['name'] = esc_html__( 'Statistics', 'total' ) . ' 6';
$templates['statistics-6']['category'] = 'statistics';
$templates['statistics-6']['content'] = <<<CONTENT
[vc_row gap="10" css=".vc_custom_1627254569785{padding-top: 60px !important;padding-bottom: 70px !important;}"][vc_column width="2/5"][vcex_heading text="My Skills &amp; Talents" tag="h2" font_size="30px" font_weight="700"][vcex_divider_dots align="left" margin="top:10px|bottom:20px" color="#bbbbbb"][vc_column_text width="650px" align="center"]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et justo ultricies, mattis felis quis, laoreet eros. Vivamus pellentesque mauris orci. Ut vitae congue ligula.[/vc_column_text][vcex_spacing][vcex_button text_transform="uppercase" font_weight="bold" font_padding="top:12px|right:20px|bottom:12px|left:20px" font_size=".8em" letter_spacing="1px"]Request a Quote[/vcex_button][/vc_column][vc_column width="3/5"][vcex_skillbar title="HTML" percentage="45" style="alt-1" bottom_margin="20px" border_radius="rounded-full" container_height="20px" percentage_font_size="10px" background="#eeeeee" color="#616161"][vcex_skillbar title="WordPress" percentage="37" style="alt-1" bottom_margin="20px" border_radius="rounded-full" container_height="20px" percentage_font_size="10px" background="#eeeeee" color="#616161"][vcex_skillbar title="Photoshop" percentage="67" style="alt-1" bottom_margin="20px" border_radius="rounded-full" container_height="20px" percentage_font_size="10px" background="#eeeeee" color="#616161"][vcex_skillbar title="SEO &amp; Marketing" percentage="90" style="alt-1" bottom_margin="20px" border_radius="rounded-full" container_height="20px" percentage_font_size="10px" background="#eeeeee" color="#616161"][/vc_column][/vc_row]
CONTENT;

$templates['statistics-7'] = array();
$templates['statistics-7']['name'] = esc_html__( 'Statistics', 'total' ) . ' 7';
$templates['statistics-7']['category'] = 'statistics';
$templates['statistics-7']['content'] = <<<CONTENT
[vc_row css=".vc_custom_1627353745255{margin-top: 40px !important;}"][vc_column][vcex_heading text="With over fifty years of experience we offer unmatched service" align="center" font_size="30px" font_weight="bold" width="650px" text_align="center" color="#143163"][vcex_spacing size="20px"][vc_column_text width="400px" align="center" text_align="center"]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et justo ultricies, mattis felis quis, laoreet eros.[/vc_column_text][vcex_spacing size="10px"][/vc_column][/vc_row][vc_row][vc_column width="1/3"][vcex_heading text="100+" bottom_margin="15px" color="#143163" font_size="30px" font_weight="bold" text_align="center"][vc_column_text text_align="center"]Lorem ipsum dolor sit amet, consectetur adipiscing elit vivamus et justo ultricies, mattis.[/vc_column_text][/vc_column][vc_column width="1/3"][vcex_heading text="24,000+" bottom_margin="15px" color="#143163" font_size="30px" font_weight="bold" text_align="center"][vc_column_text text_align="center"]Lorem ipsum dolor sit amet, consectetur adipiscing elit vivamus et justo ultricies, mattis.[/vc_column_text][/vc_column][vc_column width="1/3"][vcex_heading text="$60K" bottom_margin="15px" color="#143163" font_size="30px" font_weight="bold" text_align="center"][vc_column_text text_align="center"]Lorem ipsum dolor sit amet, consectetur adipiscing elit vivamus et justo ultricies, mattis.[/vc_column_text][/vc_column][/vc_row]
CONTENT;

$templates['statistics-8'] = array();
$templates['statistics-8']['name'] = esc_html__( 'Statistics', 'total' ) . ' 8';
$templates['statistics-8']['category'] = 'statistics';
$templates['statistics-8']['content'] = <<<CONTENT
[vc_row content_placement="middle" column_spacing="50" css=".vc_custom_1627354899036{padding-top: 50px !important;}"][vc_column width="1/2"][vcex_image source="external" external_image="{$ph_portrait}"][/vc_column][vc_column width="1/2"][vcex_heading text="256" tag="div" font_size="40px" font_weight="800"][vcex_heading text="Gigabytes of storage" bottom_margin="15px" tag="div" font_size="24px" font_weight="semibold"][vc_column_text]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et justo ultricies, mattis felis quis, laoreet eros. Vivamus pellentesque mauris orci.[/vc_column_text][vcex_divider color="accent" width="50px" align="left" height="4px" margin="top:30px|bottom:30px"][vcex_heading text="12MP" tag="div" font_size="40px" font_weight="800"][vcex_heading text="Wide-angle and telephoto cameras" bottom_margin="15px" tag="div" font_size="24px" font_weight="semibold"][vc_column_text]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et justo ultricies, mattis felis quis, laoreet eros. Vivamus pellentesque mauris orci.[/vc_column_text][vcex_divider color="accent" width="50px" align="left" height="4px" margin="top:30px|bottom:30px"][vcex_heading text="5.8in" tag="div" font_size="40px" font_weight="800"][vcex_heading text="All-screen OLED Multi-Touch display" bottom_margin="15px" tag="div" font_size="24px" font_weight="semibold"][vc_column_text]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et justo ultricies, mattis felis quis, laoreet eros. Vivamus pellentesque mauris orci.[/vc_column_text][/vc_column][/vc_row]
CONTENT;

$templates['statistics-9'] = array();
$templates['statistics-9']['name'] = esc_html__( 'Statistics', 'total' ) . ' 9';
$templates['statistics-9']['category'] = 'statistics';
$templates['statistics-9']['content'] = <<<CONTENT
[vc_row full_width="stretch_row" css=".vc_custom_1627415362002{padding-top: 80px !important;padding-bottom: 80px !important;background-color: #f7f7f7 !important;}"][vc_column][vcex_heading text="Help us save the rainforest." align="left" float="false" tag="h2" font_size="d:40px|pp:35px" font_weight="bold" width="400px" line_height="1.2" font_family="Open Sans"][vcex_spacing size="40px"][vcex_grid_container gap="60px"][vcex_icon_box heading="30%" style="two" alignment="left" icon="" heading_size="80px" heading_color="#0c7059" font_size="16px" font_color="#222222" heading_line_height="1.3"]Forests still cover about 30 percent of the world's land area, but they are disappearing at an alarming rate.[/vcex_icon_box][vcex_icon_box heading="17%" style="two" alignment="left" icon="" heading_size="80px" heading_color="#0c7059" font_size="16px" font_color="#222222" heading_line_height="1.3"]Of the Amazonian rainforest has been destroyed over the past 50 years, and losses recently have been on the rise.[/vcex_icon_box][vcex_icon_box heading="80K" style="two" alignment="left" icon="" heading_size="80px" heading_color="#0c7059" font_size="16px" font_color="#222222" heading_line_height="1.3"]Most experts agree that we are losing upwards of 80,000 acres of tropical rainforest daily.[/vcex_icon_box][/vcex_grid_container][/vc_column][/vc_row]
CONTENT;
$templates['statistics-10'] = array();
$templates['statistics-10']['name'] = esc_html__( 'Statistics', 'total' ) . ' 10';
$templates['statistics-10']['category'] = 'statistics';
$templates['statistics-10']['content'] = <<<CONTENT
[vc_section css=".vc_custom_1631735128534{padding-top: 60px !important;padding-bottom: 20px !important;}"][vc_row][vc_column][vcex_heading text="Take your business to the next level. See why we stand out from the rest." align="center" font_size="30px" font_weight="bold" width="650px" text_align="center"][/vc_column][/vc_row][vc_row remove_bottom_col_margin="true" css=".vc_custom_1631735211871{margin-bottom: 40px !important;border-top-width: 3px !important;border-right-width: 3px !important;border-bottom-width: 3px !important;border-left-width: 3px !important;padding-top: 30px !important;padding-right: 30px !important;padding-bottom: 30px !important;padding-left: 30px !important;border-left-color: #ededed !important;border-left-style: solid !important;border-right-color: #ededed !important;border-right-style: solid !important;border-top-color: #ededed !important;border-top-style: solid !important;border-bottom-color: #ededed !important;border-bottom-style: solid !important;border-radius: 10px !important;}"][vc_column width="1/2"][vcex_icon_box heading="87%" style="two" icon="" heading_size="3.8em" heading_type="div" heading_weight="bold" width="350px" css=".vc_custom_1631733685957{padding: 40px !important;}"]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et justo ultricies.[/vcex_icon_box][vcex_divider color="#fc7f60" height="3px" visibility="visible-phone" width="70%"][vcex_column_side_border background_color="#fc7f60" width="3px"][/vc_column][vc_column width="1/2"][vcex_icon_box heading="300K" style="two" icon="" heading_size="3.8em" heading_type="div" heading_weight="bold" width="350px" css=".vc_custom_1631733691497{padding: 40px !important;}"]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus et justo ultricies.[/vcex_icon_box][/vc_column][/vc_row][vc_row][vc_column][vc_column_text width="700px" align="center" text_align="center"]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tempor turpis semper dignissim sodales. Nulla bibendum, mi vitae porttitor fringilla, urna est egestas lectus, non tincidunt.[/vc_column_text][/vc_column][/vc_row][/vc_section]
CONTENT;
$templates['statistics-11'] = array();
$templates['statistics-11']['name'] = esc_html__( 'Statistics', 'total' ) . ' 11';
$templates['statistics-11']['category'] = 'statistics';
$templates['statistics-11']['content'] = <<<CONTENT
[vc_row remove_bottom_col_margin="true" css=".vc_custom_1631735531885{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column][vcex_heading text="Take your business to the next level. See why we stand out from the rest." align="center" font_size="30px" font_weight="bold" width="650px" text_align="center"][vcex_spacing size="50px"][vcex_grid_container gap="40px"][vcex_icon_box heading="Daily Visits" style="two" icon_spacing="25px" wpex_padding="40px" icon="ticon ticon-area-chart" background_color="#b1c7fc" border_radius="10px" heading_size="1em" heading_type="h3" heading_weight="bold" icon_size="3.8em" font_color="#252c5e" heading_color="#616abe" font_size="2.4em" heading_transform="uppercase" heading_letter_spacing="2px" font_weight="bold" heading_bottom_margin="0px" css=".vc_custom_1631737018145{padding-top: 80px !important;padding-bottom: 80px !important;}"]1,869[/vcex_icon_box][vcex_icon_box heading="Downloads" style="two" icon_spacing="25px" wpex_padding="40px" icon="ticon ticon-download" background_color="#a0d4ff" border_radius="10px" heading_size="1em" heading_type="h3" heading_weight="bold" icon_size="3.8em" font_color="#032955" heading_color="#198fdf" font_size="2.4em" heading_transform="uppercase" heading_letter_spacing="2px" font_weight="bold" heading_bottom_margin="0px" css=".vc_custom_1631737023896{padding-top: 80px !important;padding-bottom: 80px !important;}"]5 Million[/vcex_icon_box][vcex_icon_box heading="Connections" style="two" icon_spacing="25px" wpex_padding="40px" icon="ticon ticon-plug" background_color="#c3efd7" border_radius="10px" heading_size="1em" heading_type="h3" heading_weight="bold" icon_size="3.8em" font_color="#013b1d" heading_color="#318859" font_size="2.4em" heading_transform="uppercase" heading_letter_spacing="2px" font_weight="bold" heading_bottom_margin="0px" css=".vc_custom_1631737028024{padding-top: 80px !important;padding-bottom: 80px !important;}"]10,354[/vcex_icon_box][/vcex_grid_container][/vc_column][/vc_row]
CONTENT;
$templates['statistics-12'] = array();
$templates['statistics-12']['name'] = esc_html__( 'Statistics', 'total' ) . ' 12';
$templates['statistics-12']['category'] = 'statistics';
$templates['statistics-12']['content'] = <<<CONTENT
[vc_row remove_bottom_col_margin="true" css=".vc_custom_1631659582678{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column][vc_column_text font_size=".9em" text_transform="uppercase" color="accent" font_weight="500" letter_spacing=".5px"]About us[/vc_column_text][vcex_spacing size="25px"][vc_column_text font_size="1.8em" color="#222222"]Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tempor turpis semper dignissim sodales. Nulla bibendum, mi vitae porttitor fringilla, urna est egestas lectus, non tincidunt diam ligula eget massa. Praesent venenatis purus ut tincidunt vulputate.[/vc_column_text][vcex_spacing size="60px"][vcex_flex_container align_items="center" justify_content="space-between" row_stack_bp="sm" flex_wrap="true" flex_direction="row" gap="40px"][vcex_milestone text_align="left" number="18" caption="Years of experience" number_color="#222222" caption_color="#424242" caption_size="1.2em" caption_font="normal" number_weight="500"][vcex_milestone text_align="left" number="74" caption="Established locations" number_color="#222222" caption_color="#424242" caption_size="1.2em" caption_font="normal" number_weight="500"][vcex_milestone text_align="left" number="50" caption="Happy customers" number_color="#222222" caption_color="#424242" caption_size="1.2em" after="K" caption_font="normal" number_weight="500"][vcex_milestone text_align="left" number="4" caption="Monthly visitors" number_color="#222222" caption_color="#424242" caption_size="1.2em" after="M" caption_font="normal" number_weight="500"][/vcex_flex_container][/vc_column][/vc_row]
CONTENT;
// IMPORTANT - Space required to prevent HEREDOC errors.
?>